# Generated by Django 2.2.1 on 2019-07-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20190726_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='music',
            field=models.ImageField(default=None, upload_to='musics/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='video',
            field=models.ImageField(default=None, upload_to='videos/'),
        ),
    ]
