# Generated by Django 2.2.1 on 2019-07-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20190726_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='music',
            field=models.ImageField(default='default.mp3', upload_to='musics/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='video',
            field=models.ImageField(default='default.mp4', upload_to='videos/'),
        ),
    ]
